haha pls accept
ianmah/310-bookmarklet pull request #7
Opened 2020-09-15 23:39 UTC by jyoo980

2020-09-15 23:39 UTC, jyoo980 commented on bookmarklet.js
> -                }, 69);
magic number bad

2020-09-15 23:40 UTC, jyoo980 commented on bookmarklet.js
> +            console.log = () => {
fat arrow function go brrrr

2020-09-15 23:49 UTC, ianmah requested changes

2020-09-15 23:49 UTC, ianmah commented on bookmarklet.js
> +            console.log = () => {
this doesnt work

2020-09-15 23:56 UTC, ianmah commented on bookmarklet.js
> +            console.log = function () {
nit: did you mean to do this?

2020-09-15 23:57 UTC, jyoo980 commented on bookmarklet.js
> +            console.log = function () {
no, fixed

2020-09-16 01:02 UTC, joshflchan commented
:shipit:

2020-09-16 07:43 UTC, ianmah commented on bookmarklet.js
> +        const hahaFunnyWeedNumber = 420;
```suggestion
        const pollInterval = 69;
        const resultWaitTime = 420;
```

2020-09-16 19:01 UTC, ianmah approved these changes
🚀

2020-09-16 19:01 UTC, merged